### ISSUE TITLE
Allow customize own checkbox: change css to remove the border-radius, centering the check icon, change border-size

### ISSUE THREAD

**Issue by Trispa** [jakezatecky/react-checkbox-tree#102]

**Comment by jakezatecky** [comment]
Hellow @Trispa. Sorry for the late reply.

The checkboxes are just Font Awesome icons, which I cannot directly change in terms of border radius, size, and so on. I suppose I could role out my own custom checkboxes, but honestly making pretty icons in HTML is not my strong suit.

You do have a couple options, however.

If you prefer the native browser icons you can pass in the `nativeCheckboxes` property, and the Font Awesome checkboxes will no longer appear.

The other option is to override the CSS that uses Font Awesome. Currently, the following CSS dictates the icons used for the checkboxes:

``` css
.rct-icon {
  font-family: "FontAwesome";
  font-style: normal;
}

.rct-icon-uncheck::before {
  content: "\f096";
}

.rct-icon-check::before {
  content: "\f046";
}
```

If you have the luxury of using a font set that has other icons, you can change the font family and use whatever character that font uses for the checked/unchecked icons.
