### ISSUE TITLE
React Checkbox Tree wraps the data

### ISSUE THREAD

**Issue by agrawal-prateek** [jakezatecky/react-checkbox-tree#131]
I am using react-checkbox-tree and I found that if the width of the outside container of Tree is small, It Starts wrapping the data.

Below is a screenshot example of a higher width device-

-----------------------------------------------------------------------------------

<img width="309" alt="screen shot 2019-02-08 at 6 22 06 pm" src="https://user-images.githubusercontent.com/46881959/52479488-c6cb9980-2bce-11e9-9a91-897d658192ee.png">

-----------------------------------------------------------------------------------
And, here an example when the device width is small-

-----------------------------------------------------------------------------------

<img width="193" alt="screen shot 2019-02-08 at 6 23 26 pm" src="https://user-images.githubusercontent.com/46881959/52479521-e793ef00-2bce-11e9-9055-807dd1d702f9.png">

-----------------------------------------------------------------------------------

I have tried a lot by using custom CSS, but nothing worked. Is there any solution for this?

**Comment by jakezatecky** [comment]
Hello @agrawal-prateek, sorry for the late reply.

The default behavior is as you noted to wrap text when there is overflow. If you desire that overflow is turned into an ellipsis, you can add the following to a CSS file:

``` css
.react-checkbox-tree ol {
  width: 100%;
}

.rct-text {
  text-overflow: ellipsis;
}

.react-checkbox-tree label,
.rct-bare-label {
  display: flex;
  overflow: hidden;
  white-space: nowrap;
}

.rct-title {
  overflow: hidden;
  text-overflow: ellipsis;
}
```

If you desire to not have an ellipsis appear when there is text overflow, you can just remove those lines and the text will overflow off of the screen.
