### ISSUE TITLE
Support for RTL

### ISSUE THREAD

**Issue by dev-masih** [jakezatecky/react-checkbox-tree#182]
Hi, great job on this btw.
i have a question is there any easy way to change entire tree direction from LTR to RTL? especially when using RTL languages?

**Comment by jakezatecky** [comment]
No, but this should be an easy feature to add for the next release. I think
we can just make some CSS/style changes to accommodate RTL. Thanks for the
suggestion!

**Comment by dev-masih** [comment]
good to hear that you are going to add this feature, thanks

**Comment by jakezatecky** [comment]
Hello @dev-masih. My knowledge of RTL support is fairly limited, but I made some style adjustments as I was testing things out and wanted to know if the following layout would be what you are looking for:

![image](https://user-images.githubusercontent.com/3210703/71450950-d34ed700-2739-11ea-8ed3-c9d3eaf8334c.png)

I made these changes after applying `dir="rtl"` to the top-level `<html>` tag and applying the following CSS rules:

``` css
.react-checkbox-tree ol ol {
  padding-right: 24px;
}

.rct-icons-fa5 .rct-icon-expand-close::before {
  content: "\f053";
}
```

If that looks fine, I can add the `dir` prop to this library such that it supports RTL and applies these style changes automatically.
