### ISSUE TITLE
Label center alignment

### ISSUE THREAD

**Issue by shaozi** [jakezatecky/react-checkbox-tree#227]
**Describe the bug**
When I use material icons, the label and checkbox are not vertically central aligned. See screenshot 1, the labels are too low.

![Screen Shot 2020-10-15 at 10 28 38 AM](https://user-images.githubusercontent.com/417833/96151806-73483d80-0ed1-11eb-94ec-07448471a9f4.png)

I have to add this css to align it:

```css
.rct-text label {
  display: flex;
  flex-direction: row;
  align-items: center;
}
```

After:

![Screen Shot 2020-10-15 at 10 28 53 AM](https://user-images.githubusercontent.com/417833/96151964-9ecb2800-0ed1-11eb-964e-8a33db390ff8.png)

Should we include the styles in your build?
