### ISSUE TITLE
How can I change particular labels font size and color in react-checkbox-tree?

### ISSUE THREAD

**Issue by MohilRealloc** [jakezatecky/react-checkbox-tree#274]
hello,
how can I change particular label font size and color In react-checkbox-tree?
Thank you.

**Comment by jakezatecky** [comment]
Sorry for the very late reply.

The best way to change label font size or color is through CSS:

``` css
.rct-title {
    font-size: 18px;
    color: fuchsia;
}
```

Please let me know if you have further questions.
