### ISSUE TITLE
How to customize dropdown?

### ISSUE THREAD

**Issue by rohitkrishna094** [jakezatecky/react-checkbox-tree#298]
I want to have a different icon for dropdown arrows. I saw this issue https://github.com/jakezatecky/react-checkbox-tree/issues/76 but when I add the code given in jsfiddle, its not working for me.

Here is the codesandbox link(https://codesandbox.io/s/icy-hill-h28cy)

TLDR; In the scss file I added these

```scss
.rct-icon-expand-close::before {
  content: "\f0da";
}

.rct-icon-expand-open::before {
  content: "\f0d7";
}

```

**Comment by jakezatecky** [comment]
The way the CSS rules are written for this library, you will have to include an additional scope to be able to override the styles:

``` css
.rct-icons-fa5 .rct-icon-expand-close::before {
  content: "\f0da";
}

.rct-icons-fa5 .rct-icon-expand-open::before {
  content: "\f0d7";
}
```

You can also set the node for the icon by passing in the `icons` property to the component:

``` jsx

<CheckboxTree
    ...
    icons={{
        expandClose: <FontAwesomeIcon className="rct-icon rct-icon-expand-close" icon="chevron-right" />,
        expandOpen: <FontAwesomeIcon className="rct-icon rct-icon-expand-open" icon="chevron-down" />,
    }}
/>
```
