### ISSUE TITLE
Option to remove icon

### ISSUE THREAD

**Issue by Futuro212** [jakezatecky/react-checkbox-tree#30]
Hi,

There's a way to remove the icons placed in the tree? I just want to work with the labels on it.

Thanks :)

**Comment by jakezatecky** [comment]
@RodrigoCarvalho21 Right now you only have really one option. That is to set a CSS rule to hide the icon:

``` css
.rct-node-icon {
  display: none;
}
```
